In [8]:
#analyzing the csv file
import pandas as pd 
import glob

In [3]:
data = pd.read_csv("results.csv")
#loop through each csv file in trained models -> get lowest (val) loss and num epochs
#use pd.describe()
data.describe()

       epochs   val_loss       loss
count    17.0  16.000000  16.000000
mean    200.0   0.021000   0.021989
std       0.0   0.002833   0.002721
min     200.0   0.017498   0.019096
25%     200.0   0.019547   0.020407
50%     200.0   0.020166   0.021095
75%     200.0   0.021128   0.023046
max     200.0   0.029096   0.030042

In [48]:
#print(data)
#loop through csv files 
#append them to new csv file
#save the name?
newData = []
path = "trainedModels/*.csv"
#print(newData)
for fname in glob.glob(path):
    df = pd.read_csv(fname)
    new_row = [fname, df.loc[0][-1], df.loc[4].min(), df.loc[1][-1]]
    #create new row with name, epochs,etc
    newData.append(new_row)
    #print(df.loc[4].min())

In [58]:
#
data = pd.DataFrame(newData, columns=["name", "epochs", "val_loss", "loss"])
print(data)

                                            name    epochs  val_loss      loss
0       trainedModels\maxFalseTrueplaneFalse.csv  0.030559  0.029284  0.027282
1       trainedModels\maxNoneFalseplaneFalse.csv  0.036603  0.023433  0.027779
2      trainedModels\meanNoneFalseplaneFalse.csv  0.068005  0.024770  0.032351
3       trainedModels\minFalseTrueplaneFalse.csv  0.039515  0.030318  0.033738
4       trainedModels\minNoneFalseplaneFalse.csv  0.055445  0.028504  0.048568
5         trainedModels\minNoneTrueplaneTrue.csv  0.058058  0.029169  0.038554
6     trainedModels\NoneFalseFalseplaneFalse.csv  0.030206  0.023368  0.022672
7    trainedModels\NoneFalseTruelaputopFalse.csv  0.034104  0.022728  0.031922
8       trainedModels\NoneFalseTrueNoneFalse.csv  0.035040  0.030267  0.055016
9      trainedModels\NoneFalseTrueplaneFalse.csv  0.044566  0.025393  0.025629
10      trainedModels\NoneFalseTrueplaneTrue.csv  0.034453  0.025795  0.026277
11     trainedModels\NoneFalseTruesmallFalse.csv  0.034588  0.021421  0.024019
12       trainedModels\NonemaxTrueplaneFalse.csv  0.037624  0.024658  0.025717
13        trainedModels\NonemaxTrueplaneTrue.csv  0.045819  0.021006  0.022477
14      trainedModels\NonemeanTrueplaneFalse.csv  0.025753  0.022392  0.022785
15       trainedModels\NonemeanTrueplaneTrue.csv  0.068003  0.022186  0.027053
16       trainedModels\NoneminTrueplaneFalse.csv  0.046528  0.020647  0.068896
17        trainedModels\NoneminTrueplaneTrue.csv  0.025768  0.022788  0.032644
18     trainedModels\NoneNoneFalseplaneFalse.csv  0.052323  0.026951  0.026897
19      trainedModels\NoneNoneFalseplaneTrue.csv  0.114802  0.026527  0.033390
20     trainedModels\NoneNoneTruelaputopTrue.csv  0.097342  0.021951  0.036394
21        trainedModels\NoneNoneTrueNoneTrue.csv  0.041522  0.031078  0.034098
22      trainedModels\NoneNoneTrueplaneFalse.csv  0.092071  0.022175  0.045374
23       trainedModels\NoneNoneTrueplaneTrue.csv  0.043271  0.023523  0.032525
24       trainedModels\NoneNoneTruesmallTrue.csv  0.049218  0.030901  0.035979
25   trainedModels\NoneproductTrueplaneFalse.csv  0.044039  0.021681  0.022415
26    trainedModels\NoneproductTrueplaneTrue.csv  0.033624  0.024394  0.024931
27       trainedModels\NonesumTrueplaneFalse.csv       NaN  4.000000       NaN
28        trainedModels\NonesumTrueplaneTrue.csv       NaN  4.000000       NaN
29  trainedModels\productFalseTrueplaneFalse.csv  0.028216  0.021508  0.029203
30  trainedModels\productNoneFalseplaneFalse.csv  0.051789  0.026649  0.056261
31    trainedModels\productNoneTrueplaneTrue.csv  0.043665  0.023865  0.036240
32      trainedModels\sumFalseTrueplaneFalse.csv  0.027430  0.021342  0.044252
33      trainedModels\sumNoneFalseplaneFalse.csv  0.053393  0.023414  0.029502
34        trainedModels\sumNoneTrueplaneTrue.csv  0.054779  0.025052  0.029329

In [75]:
data.loc[data["loss"]<0.023]

                                           name    epochs  val_loss      loss
6    trainedModels\NoneFalseFalseplaneFalse.csv  0.030206  0.023368  0.022672
13       trainedModels\NonemaxTrueplaneTrue.csv  0.045819  0.021006  0.022477
14     trainedModels\NonemeanTrueplaneFalse.csv  0.025753  0.022392  0.022785
25  trainedModels\NoneproductTrueplaneFalse.csv  0.044039  0.021681  0.022415